version: 2
jobs:
  build:
    working_directory: ~/upstatejs
    docker:
      - image: circleci/node:8.6.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install NPM
          command: npm install
      - run:
          name: Test
          command: npm test
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
